import type { Metadata } from "next";
import { Inter, Ubuntu, Josefin_Sans } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ['400', '700'],
  variable: '--ubuntu'
})

const JosefinSans = Josefin_Sans({
  subsets: ["latin"],
  weight: ['400', '700'],
  variable: '--josefin-sans'
})
export const metadata: Metadata = {
  title: "Next Banking System",
  description: "A modern banking system generated by Harshal Kahar",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ubuntu.variable} ${JosefinSans.variable} ${inter}`}>{children}</body>
    </html>
  );
}
